### ISSUE TITLE
Build failure with PG13: pgl_ddl_deploy.c:74:30: error: incompatible types when assigning to type ‘const char *’ from type ‘CommandTag’

### ISSUE THREAD

**Issue by df7cb** [enova/pgl_ddl_deploy#55]
```
### PostgreSQL 13 build ###
make[2]: Verzeichnis „/home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy/build-13“ wird betreten
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -g -O2 -fdebug-prefix-map=/home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgl_ddl_deploy.o /home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy/pgl_ddl_deploy.c
/home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy/pgl_ddl_deploy.c: In function ‘sql_command_tags’:
/home/cbe/projects/postgresql/pgl-ddl-deploy/pgl-ddl-deploy/pgl_ddl_deploy.c:74:30: error: incompatible types when assigning to type ‘const char *’ from type ‘CommandTag’
   74 |         commandTag         = CreateCommandTag(parsetree);
      |                              ^~~~~~~~~~~~~~~~
make[2]: *** [<eingebaut>: pgl_ddl_deploy.o] Fehler 1
```

**Comment by cpaelzer** [comment]
And another ping ... from Ubuntu this time ... to chime in with my fellow packager - any update/ETA/status on this being needed for PG13 support?

**Comment by jfinzel** [comment]
@cpaelzer @df7cb I am working on version 2.0 which adds support for native logical replication as well as pg13.  I am actively working on it, and hope to have it within the next 2 weeks.  I will send an update if plans change.  Please let me know if you have any questions.

**Comment by jfinzel** [comment]
I have added pg13 support and pull request sent: https://github.com/enova/pgl_ddl_deploy/pull/56

@df7cb @cpaelzer but I am having issues now getting this to build with the lintian changes recently merged:
```
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package pgl-ddl-deploy
dpkg-buildpackage: source version 2.0.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Jeremy Finzel <jfinzel@enova.com>
 dpkg-source --before-build pgl_ddl_deploy
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 12)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

I'm not sure what has changed since I last built the package.  It also still fails even if I lower debhelper-compat down again to version 9.  I am still working on this but likely I can't get it finished until early next week.  Any pointers would be much appreciated!

**Comment by df7cb** [comment]
Hi,
`debhelper-compat (= NN)` is only supported in buster or later. If you are on stretch, you need to use the older `debhelper (>= NN)` format and put `NN` in `debian/compat`. The new format combines both into one line.

**Comment by jfinzel** [comment]
@df7cb thanks.  I am actually on Xenial and so reverted back to the `debian/compat`.  I have a final PR in review now.  Hoping it will be released soon.

**Comment by jfinzel** [comment]
https://github.com/enova/pgl_ddl_deploy/releases/tag/v2.0.0
